# Generated by Django 3.0.3 on 2020-05-10 11:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('is_black', models.BooleanField()),
                ('pick', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.TextField(default='[]')),
                ('deque', models.TextField(default='[]')),
                ('size', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('FINISHED', 'Finished')], default='CREATED', max_length=10)),
                ('black_deque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Deque')),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(related_name='_hand_cards_+', to='game.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid')])),
                ('auth_token', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), django.core.validators.MinLengthValidator(64)])),
                ('current_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Game')),
                ('current_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.Hand')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_finish', models.DateTimeField()),
                ('pick_finish', models.DateTimeField()),
                ('round_finish', models.DateTimeField()),
                ('black_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Card')),
                ('card_czar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Round')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.Round'),
        ),
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_deque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Deque'),
        ),
    ]
