# Generated by Django 3.0.3 on 2020-05-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
